/* AUTH TYPES */
const AUTHENTICATE = 'AUTHENTICATE';
const LOGOUT = 'LOGOUT';
const SET_DID_TRY_AL = 'SET_DID_TRY_AL';

/* TAB TYPES */
const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
const TOGGLE_APP_HEADER = 'TOGGLE_APP_HEADER';

/* USER TYPES */
const SET_USER_PROFILE_UPDATED = 'SET_USER_PROFILE_UPDATED';
const SET_USER_DETAILS = 'SET_USER_DETAILS';

/* SUBSCRIPTION TYPES */
const SET_SUBSCRIPTION_ID = 'SET_SUBSCRIPTION_ID';

/* YOGA TYPES */
const SET_YOGA_ID = 'SET_YOGA_ID';

/* DIET TYPES */
const SET_DIET_PLAN_ID = 'SET_DIET_PLAN_ID';
const SET_IS_DIET_ACTIVE = 'SET_IS_DIET_ACTIVE';

export default {
  AUTHENTICATE,
  LOGOUT,
  SET_DID_TRY_AL,
  SET_SELECTED_TAB,
  TOGGLE_APP_HEADER,
  SET_USER_DETAILS,
  SET_USER_PROFILE_UPDATED,
  SET_SUBSCRIPTION_ID,
  SET_YOGA_ID,
  SET_DIET_PLAN_ID,
  SET_IS_DIET_ACTIVE,
};
